### ISSUE TITLE
Packet does not contain leading DLE and trailing DLE/ETX

### ISSUE THREAD

**Issue by mjuenema** [mjuenema/python-TSIP#27]
```
Traceback (most recent call last):
  File "docs/examples/example2.py", line 72, in <module>
    report = gps_conn.read()
  File "/home/pi/.local/lib/python2.7/site-packages/tsip-0.3.1-py2.7.egg/tsip/hlapi.py", line 175, in read
    return Packet.unpack(unstuff(unframe(pkt)))
  File "/home/pi/.local/lib/python2.7/site-packages/tsip-0.3.1-py2.7.egg/tsip/llapi.py", line 56, in unframe
    raise ValueError('packet does not contain leading DLE and trailing DLE/ETX')
```

**Comment by jeffsf** [comment]
Not sure if this is the same issue as the one you're thinking of, but the low-level `gps.read()` constantly fails to "sync" to the start of a packet frame if it happens to start up mid-frame.

Changing the ValueError to a custom FramingError and catching it (to report and ignore it) doesn't seem to help. Once off-sync, the algorithm that looks for an even number of DLEs followed by an ETX never recovers.

**Comment by mjuenema** [comment]
Hi Jeff. Thanks for reporting this. I am certain there's a bug in the algorithm for decoding the binary data stream. 

To be honest it's been ages that I worked on this project and at the moment I wouldn't even know where I keep my Trimble GPS receivers since we moved house a few months ago. 

If you think you are able to submit a merge request that fixes the bug I'd be more than happy to include it. What would also help if you could attach a capture of the serial data stream of your GPS. What model are you using?

Markus
