### ISSUE TITLE
Sometimes tsip.GPS.read() never returns anything.

### ISSUE THREAD

**Issue by mjuenema** [mjuenema/python-TSIP#31]

**Comment by chris-mck** [comment]
Hi Markus, sorry to post on such an old ticket, but could this be related to having no timeout on the serial port?

I recently tried getting a setup running in Python 3. After applying a patch from #34 I ran a dry test with no GPS module connected, only a USB-serial cable. My script hung at GPS.read() and couldn't even Control-C to stop it (I unplugged the serial cable instead). Putting a timeout on the serial port returned an error where llapi doesn't like None (because I set the timeout):

```
Traceback (most recent call last):
  File "<my script>.py", line 19, in <module>
    report =gps_conn.read()
  File "tsip\hlapi.py", line 175, in read
    return Packet.unpack(unstuff(unframe(pkt)))
  File "tsip\llapi.py", line 53, in unframe
    if is_framed(packet):
  File "tsip\llapi.py", line 22, in is_framed
    return packet[0] == DLE and packet[-2] == DLE and packet[-1] == ETX
TypeError: 'NoneType' object is not subscriptable
```

I haven't used Github much so I'm not sure of the etiquette. Should I make separate ticket for a serial timeout?

**Comment by mjuenema** [comment]
@chris-mck Thanks for reporting this. You don't have to create a separate ticket.

As you can see, I haven't worked on *python-TSIP* for many years. I don't even know where my Trimple-GPS receivers are hiding in the garage. So please don't expect a quick resolution to this issue.
